// Generated by CoffeeScript 2.2.1
(function() {
  var cd, get_sapwn_cd, spawn_cd_by_piece_count;

  spawn_cd_by_piece_count = (function() {
    var i, len, ref, results;
    ref = [10, 10, 10, 12, 14, 16, 18, 20, 24, 28, 32, 36, 40, 44, 50];
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      cd = ref[i];
      results.push(cd * 10);
    }
    return results;
  })();

  get_sapwn_cd = function(piece_count) {
    if (piece_count < 1 || piece_count > 16) {
      throw "invalid piece count";
    }
    return spawn_cd_by_piece_count[piece_count - 1];
  };

  window.rule.spawn = {
    spawn_cd: get_sapwn_cd
  };

}).call(this);

//# sourceMappingURL=spawn.js.map
