// Generated by CoffeeScript 2.2.1
(function() {
  var end_game, init_demo, on_gametick, on_gametick_game_end;

  on_gametick = function(evt) {
    game.ai_think_round(battleground.instance);
    game.move_round(battleground.instance);
    game.assist_round(battleground.instance);
    game.recover_round(battleground.instance);
    game.attack_round(battleground.instance);
    game.end_of_rounds(battleground.instance);
    return game.render_gametick();
  };

  on_gametick_game_end = function(evt) {
    return game.render_gametick();
  };

  end_game = function(evt) {
    ev.unhook('gametick', on_gametick);
    ev.hook('gametick', on_gametick_game_end);
    preview.disable();
    if (evt.result === 'draw') {
      return ui.gamestat.value = 'draw!';
    } else if (evt.result === 'win') {
      return ui.gamestat.value = evt.player + ' wins!';
    } else {
      return ui.gamestat.value = 'game ended with unknown status';
    }
  };

  init_demo = function() {
    ev.init();
    input.init();
    operation.init();
    preview.init();
    preview.set_color('white');
    battleground.init();
    battle.init();
    effect.init();
    ev.hook('gametick', on_gametick);
    ev.hook('move_round_begin', operation.handle_cached_operations);
    ev.hook('game_end', end_game);
    ai.init();
    return ai.activate('black');
  };

  window.game.init_demo = init_demo;

}).call(this);

//# sourceMappingURL=demo.js.map
