// Generated by CoffeeScript 1.8.0
(function() {
  var init_demo, on_gametick;

  on_gametick = function(evt) {
    game.ai_think_round();
    game.move_round();
    game.assist_round();
    game.recover_round();
    game.attack_round();
    return game.render_gametick();
  };

  init_demo = function() {
    ev.init();
    input.init();
    operation.init();
    preview.init();
    preview.set_color('white');
    board.init();
    battle.init();
    effect.init();
    network.init();
    ev.hook('gametick', on_gametick);
    ev.hook('move_round_begin', operation.handle_cached_operations);
    ai.init();
    return ai.activate('black');
  };

  window.game.init_demo = init_demo;

}).call(this);
