// Generated by CoffeeScript 2.2.1
(function() {
  var init_demo, on_gametick;

  on_gametick = function(evt) {
    game.ai_think_round(battleground.instance);
    game.move_round(battleground.instance);
    game.assist_round(battleground.instance);
    game.recover_round(battleground.instance);
    game.attack_round(battleground.instance);
    //gamestate.send_current_state()
    return game.render_gametick();
  };

  init_demo = function() {
    ev.init();
    input.init();
    operation.init();
    preview.init();
    preview.set_color('white');
    battleground.init();
    battle.init();
    effect.init();
    network.init();
    ev.hook('gametick', on_gametick);
    ev.hook('move_round_begin', operation.handle_cached_operations);
    ai.init();
    return ai.activate('black');
  };

  window.game.init_demo = init_demo;

}).call(this);

//# sourceMappingURL=demo.js.map
