// Generated by CoffeeScript 1.8.0
(function() {
  var init_guest, on_gametick, sync_up_gamestate;

  sync_up_gamestate = function() {
    var _results;
    gamestate.to_next_state();
    if (gamestate.to_next_state()) {
      _results = [];
      while (gamestate.cache_size() > 5) {
        _results.push(gamestate.to_next_state());
      }
      return _results;
    }
  };

  on_gametick = function(evt) {
    operation.send_cached_operations();
    sync_up_gamestate();
    return game.render_gametick();
  };

  init_guest = function() {
    ev.init();
    input.init();
    operation.init();
    preview.init();
    gamestate.init();
    board.init();
    effect.init();
    network.init();
    return ev.hook('gametick', on_gametick);
  };

  window.game.init_guest = init_guest;

}).call(this);
