// Generated by CoffeeScript 2.2.1
(function() {
  var init_guest, on_gametick, state_buf, sync_up_gamestate;

  state_buf = 0;

  sync_up_gamestate = function() {
    var suceeded;
    suceeded = false;
    while (gamestate.cache_size() > state_buf) {
      suceeded = gamestate.to_next_state();
    }
    return suceeded;
  };

  on_gametick = function(evt) {
    operation.send_cached_operations();
    if (sync_up_gamestate()) {
      game.render_gametick();
      if (state_buf > 1) {
        return state_buf -= 0.1;
      }
    } else {
      if (state_buf < 5) {
        return state_buf += 1;
      }
    }
  };

  init_guest = function() {
    ev.init();
    input.init();
    operation.init();
    preview.init();
    preview.set_color('black');
    gamestate.init();
    board.init();
    effect.init();
    network.init();
    return ev.hook('gametick', on_gametick);
  };

  window.game.init_guest = init_guest;

}).call(this);
