// Generated by CoffeeScript 2.2.1
(function() {
  var init_host, on_gametick;

  on_gametick = function(evt) {
    game.move_round(battleground.instance);
    game.assist_round(battleground.instance);
    game.recover_round(battleground.instance);
    game.attack_round(battleground.instance);
    gamestate.send_current_state();
    return game.render_gametick();
  };

  init_host = function() {
    ev.init();
    input.init();
    operation.init();
    preview.init();
    preview.set_color('white');
    battleground.init();
    battle.init();
    effect.init();
    network.init();
    ev.hook('gametick', on_gametick);
    return ev.hook('move_round_begin', operation.handle_cached_operations);
  };

  window.game.init_host = init_host;

}).call(this);

//# sourceMappingURL=host.js.map
