// Generated by CoffeeScript 2.2.1
(function() {
  var do_start, end_game, init_host, on_gametick, on_gametick_game_end, start_game;

  on_gametick = function(evt) {
    game.move_round(battleground.instance);
    game.assist_round(battleground.instance);
    game.recover_round(battleground.instance);
    game.attack_round(battleground.instance);
    game.end_of_rounds(battleground.instance);
    gamestate.send_current_state();
    return game.render_gametick();
  };

  on_gametick_game_end = function(evt) {
    gamestate.send_current_state();
    return game.render_gametick();
  };

  end_game = function(evt) {
    ev.unhook('gametick', on_gametick);
    ev.hook('gametick', on_gametick_game_end);
    gamestate.end_game(evt.result, evt.player);
    return preview.disable();
  };

  start_game = function() {
    console.log('game starts from state:', gamestate.current());
    switch (gamestate.current()) {
      case 'ready':
        return do_start();
      default:
        init_host();
        return do_start();
    }
  };

  do_start = function() {
    gamestate.start_game('white');
    return game.start();
  };

  init_host = function() {
    game.stop();
    ev.init();
    input.init();
    operation.init();
    preview.init();
    preview.set_color('white');
    gamestate.init();
    battleground.init();
    battle.init();
    effect.init();
    network.init();
    ev.hook('gametick', on_gametick);
    ev.hook('move_round_begin', operation.handle_cached_operations);
    ev.hook('game_end', end_game);
    return ev.hook('game_start', start_game);
  };

  window.game.init_host = init_host;

}).call(this);

//# sourceMappingURL=host.js.map
