// Generated by CoffeeScript 1.8.0
(function() {
  var init_observer, on_gametick;

  on_gametick = function(evt) {
    var _results;
    if (gamestate.to_next_state()) {
      game.render_gametick();
      _results = [];
      while (gamestate.cache_size() > 5) {
        gamestate.to_next_state();
        _results.push(game.render_gametick());
      }
      return _results;
    }
  };

  init_observer = function() {
    ev.init();
    gamestate.init();
    board.init();
    effect.init();
    return ev.hook('gametick', on_gametick);
  };

  window.game.init_observer = init_observer;

}).call(this);
