// Generated by CoffeeScript 2.2.1
(function() {
  var init_observer, on_gametick;

  on_gametick = function(evt) {
    var results;
    if (gamestate.to_next_state()) {
      game.render_gametick();
      results = [];
      while (gamestate.cache_size() > 5) {
        gamestate.to_next_state();
        results.push(game.render_gametick());
      }
      return results;
    }
  };

  init_observer = function() {
    ev.init();
    gamestate.init();
    board.init();
    effect.init();
    return ev.hook('gametick', on_gametick);
  };

  window.game.init_observer = init_observer;

}).call(this);
