// Generated by CoffeeScript 1.8.0
(function() {
  var connect, init_connection, login, me, my_id, peer, send_data, wait;

  my_id = null;

  me = null;

  peer = null;

  wait = function(callback) {
    return me.on('connection', function(conn) {
      return init_connection(conn, function() {
        return callback(conn.peer);
      });
    });
  };

  connect = function(id, callback) {
    var conn;
    conn = me.connect(id);
    return conn.on('open', function() {
      return init_connection(conn, callback);
    });
  };

  init_connection = function(conn, callback) {
    conn.on('data', function(data) {
      return ev.trigger('network_in', {
        data: data
      });
    });
    ev.hook('network_out', function(evt) {
      return send_data(conn, evt.data);
    });
    return callback();
  };

  send_data = function(conn, data) {
    return conn.send(data);
  };

  login = function(id, callback) {
    me = new Peer(id, {
      key: '6l7puzc60rgujtt9'
    });
    return me.on('open', function(id) {
      my_id = id;
      return callback();
    });
  };

  window.network = {
    wait: wait,
    connect: connect,
    login: login
  };

}).call(this);
