// Generated by CoffeeScript 2.2.1
(function() {
  var connect, init_connection, login, me, peer_error_callbacks, peer_error_handler, wait;

  me = null;

  peer_error_callbacks = {};

  peer_error_handler = function(err) {
    var name;
    console.log(err);
    return typeof peer_error_callbacks[name = err.type] === "function" ? peer_error_callbacks[name](err) : void 0;
  };

  wait = function(callback) {
    return me.on('connection', function(conn) {
      init_connection(conn);
      return callback(conn.peer);
    });
  };

  connect = function(id, callback_success, callback_failure) {
    var conn;
    conn = me.connect(id);
    conn.on('open', function() {
      init_connection(conn);
      return callback_success();
    });
    return peer_error_callbacks['peer-unavailable'] = function() {
      return callback_failure();
    };
  };

  init_connection = function(conn) {
    conn.on('data', function(data) {
      return network.incoming(data);
    });
    return network.set_output_channel(conn);
  };

  login = function(id, callback_success, callback_failure) {
    me = new Peer(id, {
      key: '6l7puzc60rgujtt9'
    });
    me.on('open', function(id) {
      return callback_success();
    });
    me.on('error', peer_error_handler);
    return peer_error_callbacks['network'] = function() {
      me = null;
      return callback_failure();
    };
  };

  window.peer_server = {wait, connect, login};

}).call(this);

//# sourceMappingURL=peer_server.js.map
