// Generated by CoffeeScript 2.2.1
(function() {
  var answer_remote, change_status, create_local_offer, data, err_handler, get_clipboard, hook_data_channel, init, init_data_channel, local_answer_onclick, local_offer_onclick, receive_data_channel, remote_onpaste, set_clipboard, status_binds;

  data = {
    'status': ['host', 'begin'],
    'connection': 'connection',
    'channel': 'channel'
  };

  change_status = function(status) {
    var phase, type;
    data.status = status;
    [type, phase] = status;
    return status_binds[type][phase]();
  };

  status_binds = {
    'host': {
      'begin': function() {
        ui.enable(ui.local_offer_btn);
        ui.hide(ui.local_answer_btn);
        ui.hide(ui.p2p_paste);
        return ui.p2p_status.value = 'Please copy and send your offer to your peer.';
      },
      'pending': function() {
        ui.enable(ui.local_offer_btn);
        ui.hide(ui.local_answer_btn);
        ui.enable(ui.p2p_paste);
        return ui.p2p_status.value = 'Please paste the answer you received from your peer below.';
      },
      'connected': function() {
        ui.hide(ui.p2p_panel_ctrl);
        ui.hide(ui.p2p_paste);
        ui.hide(ui.ai_panel);
        return ui.p2p_status.value = 'You are connected to your peer as the host.';
      }
    },
    'guest': {
      'begin': function() {
        ui.hide(ui.local_offer_btn);
        ui.disable(ui.local_answer_btn);
        ui.enable(ui.p2p_paste);
        return ui.p2p_status.value = 'Please paste the offer you received from your peer below.';
      },
      'pending': function() {
        ui.hide(ui.local_offer_btn);
        ui.enable(ui.local_answer_btn);
        ui.hide(ui.p2p_paste);
        return ui.p2p_status.value = 'Please copy and send the answer to your peer.';
      },
      'connected': function() {
        ui.hide(ui.p2p_panel_ctrl);
        ui.hide(ui.p2p_paste);
        ui.hide(ui.ai_panel);
        return ui.p2p_status.value = 'You are connected to your peer as the guest.';
      }
    }
  };

  init = function() {
    ui.hide(ui.account_panel);
    ui.enable(ui.p2p_panel);
    change_status(data.status);
    data.connection = new RTCPeerConnection({
      iceServers: [
        {
          urls: []
        }
      ]
    });
    init_data_channel(data.connection);
    data.connection.ondatachannel = receive_data_channel;
    return ui.p2p_paste.addEventListener('paste', remote_onpaste);
  };

  set_clipboard = function(message) {
    var dummy;
    dummy = document.createElement("input");
    document.body.appendChild(dummy);
    dummy.setAttribute("value", message);
    dummy.select();
    document.execCommand("copy");
    return document.body.removeChild(dummy);
  };

  get_clipboard = function(evt) {
    return evt.clipboardData.getData('Text');
  };

  init_data_channel = function(conn) {
    data.channel = conn.createDataChannel('data');
    console.log(data.channel.binaryType);
    return hook_data_channel(data.channel);
  };

  receive_data_channel = function(e) {
    console.log('received channel', e);
    data.channel = e.channel;
    return hook_data_channel(data.channel);
  };

  create_local_offer = function() {
    return data.connection.createOffer().then((des) => {
      return data.connection.setLocalDescription(des).catch(err_handler);
    }).catch(err_handler);
  };

  local_offer_onclick = function() {
    var sdp;
    sdp = null;
    create_local_offer().then(() => {
      return sdp = JSON.stringify(data.connection.localDescription);
    });
    setTimeout((() => {
      return set_clipboard(sdp);
    }), 1000);
    return change_status(['host', 'pending']);
  };

  remote_onpaste = function(evt) {
    var phase, type;
    [type, phase] = data.status;
    if (type === 'host' && phase === 'pending') {
      answer_remote(get_clipboard(evt));
    }
    if (type === 'guest' && phase === 'begin') {
      answer_remote(get_clipboard(evt));
      return change_status(['guest', 'pending']);
    }
  };

  local_answer_onclick = function() {
    return set_clipboard(JSON.stringify(data.connection.localDescription));
  };

  answer_remote = function(remote_sdp) {
    var remote_des;
    remote_des = new RTCSessionDescription(JSON.parse(remote_sdp));
    return data.connection.setRemoteDescription(remote_des).then(() => {
      return data.connection.createAnswer().then((des) => {
        return data.connection.setLocalDescription(des).catch(err_handler);
      }).catch(err_handler);
    }).catch(err_handler);
  };

  hook_data_channel = function(data_channel) {
    data_channel.onopen = function(e) {
      var phase, type;
      console.log('channel is open', e);
      [type, phase] = data.status;
      change_status([type, 'connected']);
      network.set_output_channel(data_channel);
      if (data.status[0] === 'guest') {
        return mode.play_as_guest();
      } else {
        return mode.play_as_host();
      }
    };
    data_channel.onmessage = function(e) {
      return network.incoming(e.data);
    };
    return data_channel.onclose = function() {
      ui.p2p_status.value = "You have lost connection to your peer.";
      return console.log('channel closed');
    };
  };

  err_handler = function(err) {
    ui.p2p_status.value = "Network error occured.";
    return console.log(err);
  };

  window.peer = {init, change_status, local_offer_onclick, local_answer_onclick, remote_onpaste};

}).call(this);

//# sourceMappingURL=peer.js.map
