// Generated by CoffeeScript 2.2.1
(function() {
  var get_state, init, on_end_of_rounds, on_render, set_state;

  init = function() {
    battleground.instance = new board.Board(true);
    battleground.instance.set_out_board();
    ev.hook('end_of_rounds', on_end_of_rounds);
    return ev.hook('render', on_render);
  };

  on_end_of_rounds = function(evt) {
    var bk, wk;
    wk = battleground.instance.count_piece('king', 'white');
    bk = battleground.instance.count_piece('king', 'black');
    if (wk === 0 && bk === 0) {
      return ev.trigger_now('game_end', {
        result: 'draw'
      });
    } else if (wk === 0) {
      return ev.trigger_now('game_end', {
        result: 'win',
        player: 'black'
      });
    } else if (bk === 0) {
      return ev.trigger_now('game_end', {
        result: 'win',
        player: 'white'
      });
    }
  };

  on_render = function(evt) {
    return paint.board(ui.ctx.static);
  };

  get_state = function() {
    return board.serialize(battleground.instance);
  };

  set_state = function(buffer) {
    return board.deserialize(buffer, battleground.instance);
  };

  window.battleground = {
    init,
    instance: null,
    get_state,
    set_state
  };

}).call(this);

//# sourceMappingURL=battleground.js.map
