// Generated by CoffeeScript 1.8.0
(function() {
  var cache_size, get_state, init, on_network_gamestate_in, send_current_state, set_state, state_queue, to_next_state;

  state_queue = [];

  to_next_state = function() {
    if (!state_queue.length > 0) {
      return false;
    }
    set_state(state_queue.shift());
    return true;
  };

  get_state = function() {
    return {
      board: board.get_state(),
      effect: effect.get_state()
    };
  };

  set_state = function(state) {
    board.set_state(state.board);
    return effect.set_state(state.effect);
  };

  on_network_gamestate_in = function(evt) {
    return state_queue.push(evt.gamestate);
  };

  send_current_state = function() {
    var state;
    state = get_state();
    return ev.trigger_now('network_out_gamestate', {
      gamestate: state
    });
  };

  cache_size = function() {
    return state_queue.length;
  };

  init = function() {
    return ev.hook('network_in_gamestate', on_network_gamestate_in);
  };

  window.gamestate = {
    init: init,
    get_state: get_state,
    set_state: set_state,
    to_next_state: to_next_state,
    cache_size: cache_size,
    send_current_state: send_current_state
  };

}).call(this);
