// Generated by CoffeeScript 1.8.0
(function() {
  var init, on_challenge_accepted, on_challenge_clicked, on_challenge_failed, on_challenged, on_login_clicked, on_login_failed, on_login_succeeded;

  init = function() {
    ui.login_button.onclick = on_login_clicked;
    return ui.challenge_button.onclick = on_challenge_clicked;
  };

  on_login_clicked = function() {
    var id;
    id = ui.player_id.value;
    if (!id) {
      return;
    }
    ui.player_id.readOnly = true;
    ui.set_button_text(ui.login_button, 'logging in...');
    ui.disable_button(ui.login_button);
    return network.login(id, on_login_succeeded);
  };

  on_challenge_clicked = function() {
    var id;
    id = ui.opponent_id.value;
    if (!id) {
      return;
    }
    ui.opponent_id.readOnly = true;
    ui.set_button_text(ui.challenge_button, 'sending request...');
    ui.disable_button(ui.challenge_button);
    return network.connect(id, on_challenge_accepted);
  };

  on_login_succeeded = function() {
    ui.set_button_text(ui.login_button, 'logged in');
    ui.enable_button(ui.challenge_button);
    return network.wait(on_challenged);
  };

  on_login_failed = function() {};

  on_challenge_accepted = function() {
    ui.set_button_text(ui.challenge_button, 'challenge was accepted');
    game.stop();
    game.init_observer();
    return game.start();
  };

  on_challenge_failed = function() {};

  on_challenged = function(challenger_id) {
    ui.opponent_id.readOnly = true;
    ui.opponent_id.value = challenger_id;
    ui.disable_button(ui.challenge_button);
    return ui.set_button_text(ui.challenge_button, 'challenged you');
  };

  window.account = {
    init: init
  };

}).call(this);
