// Generated by CoffeeScript 1.8.0
(function() {
  var assist_queue, attack_queue, handle_assist, handle_assist_queue, handle_attack, handle_attack_queue, init, on_battle_assist, on_battle_attack;

  assist_queue = [];

  attack_queue = [];

  on_battle_assist = function(evt) {
    return assist_queue.push(evt);
  };

  on_battle_attack = function(evt) {
    return attack_queue.push(evt);
  };

  handle_assist_queue = function() {
    var _results;
    _results = [];
    while (assist_queue.length > 0) {
      _results.push(handle_assist(assist_queue.shift()));
    }
    return _results;
  };

  handle_attack_queue = function() {
    var _results;
    _results = [];
    while (attack_queue.length > 0) {
      _results.push(handle_attack(attack_queue.shift()));
    }
    return _results;
  };

  handle_assist = function(evt) {
    return evt.astee.enhance(evt.enhancement);
  };

  handle_attack = function(evt) {
    return evt.atkee.inflict(evt.damage);
  };

  init = function() {
    ev.hook('battle_assist', on_battle_assist);
    ev.hook('battle_attack', on_battle_attack);
    ev.hook('assist_round', handle_assist_queue);
    return ev.hook('attack_round', handle_attack_queue);
  };

  window.battle = {
    init: init
  };

}).call(this);
