// Generated by CoffeeScript 1.8.0
(function() {
  var assist_queue, handle_assist, handle_assist_queue, init, on_battle_assist;

  assist_queue = [];

  on_battle_assist = function(evt) {
    return assist_queue.push(evt);
  };

  handle_assist_queue = function() {
    var _results;
    _results = [];
    while (assist_queue.length > 0) {
      _results.push(handle_assist(assist_queue.shift()));
    }
    return _results;
  };

  handle_assist = function(evt) {
    evt.astee.shield_total += evt.enhancement[0];
    evt.astee.shield += evt.enhancement[0];
    return evt.astee.shield_heal += evt.enhancement[1];
  };

  init = function() {
    ev.hook('battle_assist', on_battle_assist);
    return ev.hook('assist_round', handle_assist_queue);
  };

  window.battle = {
    init: init
  };

}).call(this);
