// Generated by CoffeeScript 1.8.0
(function() {
  var coord_equal, coord_to_pos, hoop, pos_to_coord;

  hoop = function(num, _arg) {
    var range_lower, range_upper;
    range_lower = _arg[0], range_upper = _arg[1];
    if (num < range_lower) {
      num = range_lower;
    }
    if (num > range_upper) {
      num = range_upper;
    }
    return num;
  };

  coord_to_pos = function(_arg) {
    var pos_x, pos_y, x, y;
    x = _arg[0], y = _arg[1];
    pos_x = settings.grid_size * (x - 0.5);
    pos_y = settings.grid_size * (y - 0.5);
    return [pos_x, pos_y];
  };

  pos_to_coord = function(_arg) {
    var coord_x, coord_y, x, y;
    x = _arg[0], y = _arg[1];
    coord_x = hoop(Math.floor(x / settings.grid_size) + 1, [1, 8]);
    coord_y = hoop(Math.floor(y / settings.grid_size) + 1, [1, 8]);
    return [coord_x, coord_y];
  };

  coord_equal = function(coord_1, coord_2) {
    return coord_1[0] === coord_2[0] && coord_1[1] === coord_2[1];
  };

  window.calc = {
    coord_to_pos: coord_to_pos,
    pos_to_coord: pos_to_coord,
    coord_equal: coord_equal
  };

}).call(this);
