// Generated by CoffeeScript 1.8.0
(function() {
  var Assist, Attack, effects_assist, effects_attack, init, on_battle_assist, on_battle_attack, render_all;

  Assist = (function() {
    function Assist(coord_from, coord_to) {
      this.coord_from = coord_from;
      this.coord_to = coord_to;
    }

    Assist.prototype.render = function(ctx) {
      var to_x, to_y, x, y, _ref, _ref1, _ref2;
      _ref = calc.shrink_segment(calc.coord_to_pos(this.coord_from), calc.coord_to_pos(this.coord_to)), (_ref1 = _ref[0], x = _ref1[0], y = _ref1[1]), (_ref2 = _ref[1], to_x = _ref2[0], to_y = _ref2[1]);
      shape.save_style(ctx);
      shape.set_style(ctx, shape.style_blue_tp);
      shape.arrow(ctx, x, y, to_x, to_y);
      return shape.restore_style(ctx);
    };

    return Assist;

  })();

  Attack = (function() {
    function Attack(coord_from, coord_to) {
      this.coord_from = coord_from;
      this.coord_to = coord_to;
      this.transparency = 1;
    }

    Attack.prototype.render = function(ctx) {
      var to_x, to_y, x, y, _ref, _ref1, _ref2;
      _ref = calc.shrink_segment(calc.coord_to_pos(this.coord_from), calc.coord_to_pos(this.coord_to)), (_ref1 = _ref[0], x = _ref1[0], y = _ref1[1]), (_ref2 = _ref[1], to_x = _ref2[0], to_y = _ref2[1]);
      shape.save_style(ctx);
      shape.set_style(ctx, "rgba(255, 0, 0, " + this.transparency + ")");
      ctx.lineWidth = 3;
      shape.arrow(ctx, x, y, to_x, to_y, 10);
      shape.restore_style(ctx);
      this.transparency -= 0.2;
      if (this.transparency >= 0.2) {
        return true;
      } else {
        return false;
      }
    };

    return Attack;

  })();

  effects_assist = [];

  effects_attack = [];

  on_battle_assist = function(evt) {
    return effects_assist.push(new Assist(evt.coord_from, evt.coord_to));
  };

  on_battle_attack = function(evt) {
    return effects_attack.push(new Attack(evt.coord_from, evt.coord_to));
  };

  render_all = function() {
    var ctx, e, i, to_be_continued, _i, _j, _len, _len1;
    ctx = ui.ctx["static"];
    for (_i = 0, _len = effects_assist.length; _i < _len; _i++) {
      e = effects_assist[_i];
      e.render(ctx);
    }
    effects_assist = [];
    for (i = _j = 0, _len1 = effects_attack.length; _j < _len1; i = ++_j) {
      e = effects_attack[i];
      to_be_continued = e.render(ctx);
      if (!to_be_continued) {
        delete effects_attack[i];
      }
    }
    return effects_attack = effects_attack.filter(function(e) {
      return e != null;
    });
  };

  init = function() {
    ev.hook('battle_assist', on_battle_assist);
    ev.hook('battle_attack', on_battle_attack);
    return ev.hook('render', render_all);
  };

  window.effect = {
    init: init
  };

}).call(this);
