// Generated by CoffeeScript 1.8.0
(function() {
  var Assist, effects_assist, init, on_battle_assist, render_all;

  Assist = (function() {
    function Assist(coord_from, coord_to) {
      this.coord_from = coord_from;
      this.coord_to = coord_to;
    }

    Assist.prototype.render = function(ctx) {
      var to_x, to_y, x, y, _ref, _ref1, _ref2;
      _ref = calc.shrink_segment(calc.coord_to_pos(this.coord_from), calc.coord_to_pos(this.coord_to)), (_ref1 = _ref[0], x = _ref1[0], y = _ref1[1]), (_ref2 = _ref[1], to_x = _ref2[0], to_y = _ref2[1]);
      return shape.arrow(ctx, x, y, to_x, to_y);
    };

    return Assist;

  })();

  effects_assist = [];

  on_battle_assist = function(evt) {
    return effects_assist.push(new Assist(evt.coord_from, evt.coord_to));
  };

  render_all = function() {
    var ctx, e, _i, _len;
    ctx = ui.ctx["static"];
    shape.save_style(ctx);
    shape.set_style(ctx, shape.style_blue_tp);
    for (_i = 0, _len = effects_assist.length; _i < _len; _i++) {
      e = effects_assist[_i];
      e.render(ctx);
    }
    shape.restore_style(ctx);
    return effects_assist = [];
  };

  init = function() {
    ev.hook('battle_assist', on_battle_assist);
    return ev.hook('render', render_all);
  };

  window.effect = {
    init: init
  };

}).call(this);
