// Generated by CoffeeScript 1.8.0
(function() {
  var handle_operation, handle_operation_queue, init, next_tick, on_game_operations, on_gametick, on_render, queue, start;

  queue = [];

  handle_operation_queue = function() {
    var _results;
    _results = [];
    while (queue.length > 0) {
      _results.push(handle_operation(queue.shift()));
    }
    return _results;
  };

  handle_operation = function(op_evt) {
    return op_evt.piece.move_to(op_evt.coord_to);
  };

  on_gametick = function(evt) {
    handle_operation_queue();
    return ev.trigger('render', {});
  };

  on_render = function(evt) {
    shape.clear_canvas(ui.ctx["static"]);
    return paint.board(ui.ctx["static"]);
  };

  on_game_operations = function(evt) {
    return queue.push(evt);
  };

  init = function() {
    ev.hook('gametick', on_gametick);
    ev.hook('render', on_render);
    return ev.hook('op_movepiece', on_game_operations);
  };

  next_tick = function() {
    return ev.trigger('gametick', {});
  };

  start = function() {
    return setInterval(next_tick, 100);
  };

  window.game = {
    init: init,
    start: start
  };

}).call(this);
