// Generated by CoffeeScript 1.8.0
(function() {
  var handle_operation, handle_operation_queue, init, next_tick, on_game_operation, on_gametick, on_render, operation_queue, start;

  operation_queue = [];

  handle_operation_queue = function() {
    var _results;
    _results = [];
    while (operation_queue.length > 0) {
      _results.push(handle_operation(operation_queue.shift()));
    }
    return _results;
  };

  handle_operation = function(op_evt) {
    var moves;
    if (!op_evt.piece.is_onboard()) {
      return;
    }
    moves = op_evt.piece.valid_moves();
    if (calc.coord_one_of(op_evt.coord_to, moves.regular)) {
      return ev.trigger('battle_move', {
        piece: op_evt.piece,
        coord_to: op_evt.coord_to
      });
    }
  };

  on_gametick = function(evt) {
    ev.trigger('move_round_begin', {});
    ev.trigger('move_round', {});
    ev.trigger('move_round_end', {});
    ev.trigger('assist_round_begin', {});
    ev.trigger('assist_round', {});
    ev.trigger('assist_round_end', {});
    ev.trigger('recover_round_begin', {});
    ev.trigger('recover_round', {});
    ev.trigger('recover_round_end', {});
    ev.trigger('attack_round_begin', {});
    ev.trigger('attack_round', {});
    ev.trigger('attack_round_end', {});
    shape.clear_canvas(ui.ctx["static"]);
    return ev.trigger('render', {});
  };

  on_render = function(evt) {
    return paint.board(ui.ctx["static"]);
  };

  on_game_operation = function(evt) {
    return operation_queue.push(evt);
  };

  init = function() {
    ev.hook('gametick', on_gametick);
    ev.hook('render', on_render);
    ev.hook('op_movepiece', on_game_operation);
    return ev.hook('move_round_begin', handle_operation_queue);
  };

  next_tick = function() {
    return ev.trigger('gametick', {});
  };

  start = function() {
    return setInterval(next_tick, 100);
  };

  window.game = {
    init: init,
    start: start
  };

}).call(this);
