// Generated by CoffeeScript 1.8.0
(function() {
  var ctx, cvs, init_all, init_cvs, set_canvas_attr;

  ctx = {
    animate: null,
    "static": null,
    background: null
  };

  cvs = {
    animate: null,
    "static": null,
    background: null
  };

  init_cvs = function(name) {
    cvs[name] = document.getElementById(name);
    return ctx[name] = cvs[name].getContext('2d');
  };

  set_canvas_attr = function(cvs, z_index, size) {
    cvs.style.border = "solid #000 " + settings.cvs_border_width + "px";
    cvs.style.position = "absolute";
    cvs.style.cursor = "pointer";
    cvs.style['z-index'] = "" + z_index;
    return cvs.width = cvs.height = size;
  };

  init_all = function() {
    init_cvs('background');
    init_cvs('static');
    init_cvs('animate');
    game.cvs_bounding_rect = cvs.animate.getBoundingClientRect();
    set_canvas_attr(cvs.background, 1, settings.cvs_size);
    set_canvas_attr(cvs["static"], 2, settings.cvs_size);
    set_canvas_attr(cvs.animate, 3, settings.cvs_size);
    ctx["static"].font = settings.piece_font;
    ctx.animate.font = settings.piece_font;
    paint.background(ctx.background, settings.cvs_size);
    return game.textarea = document.getElementById('mousepos');
  };

  window.game = {
    init_all: init_all,
    cvs: cvs,
    ctx: ctx,
    cvs_bounding_rect: null,
    textarea: null
  };

}).call(this);
