// Generated by CoffeeScript 1.8.0
(function() {
  var get_mouse_pos, init, on_user_mousedown, on_user_mousemove, on_user_mouseup;

  get_mouse_pos = function(evt) {
    var mouse_x, mouse_y;
    mouse_x = evt.clientX - game.cvs_bounding_rect.left - settings.cvs_border_width;
    mouse_y = evt.clientY - game.cvs_bounding_rect.top - settings.cvs_border_width;
    return [mouse_x, mouse_y];
  };

  on_user_mousedown = function(evt) {
    var pos;
    pos = get_mouse_pos(evt);
    return ev.trigger('mousedown', {
      pos: pos
    });
  };

  on_user_mouseup = function(evt) {
    var pos;
    pos = get_mouse_pos(evt);
    return ev.trigger('mouseup', {
      pos: pos
    });
  };

  on_user_mousemove = function(evt) {
    var pos;
    pos = get_mouse_pos(evt);
    return ev.trigger('mousemove', {
      pos: pos
    });
  };

  init = function() {
    game.cvs.animate.addEventListener("mousedown", on_user_mousedown, false);
    game.cvs.animate.addEventListener("mouseup", on_user_mouseup, false);
    return game.cvs.animate.addEventListener("mousemove", on_user_mousemove, false);
  };

  window.input = {
    init: init
  };

}).call(this);
