// Generated by CoffeeScript 1.8.0
(function() {
  var init, logging_evts, on_gametick, tick_count;

  tick_count = 0;

  on_gametick = function() {
    tick_count++;
    if (tick_count % 100 === 0) {
      return console.log('tick', tick_count);
    }
  };

  logging_evts = ['pick', 'drop', 'op_movepiece', 'battle_attack'];

  init = function() {
    var evt_name, _i, _len, _results;
    ev.hook('gametick', on_gametick);
    _results = [];
    for (_i = 0, _len = logging_evts.length; _i < _len; _i++) {
      evt_name = logging_evts[_i];
      _results.push(ev.hook(evt_name, (function(evt_name) {
        return function(evt) {
          return console.log(evt_name, evt);
        };
      })(evt_name)));
    }
    return _results;
  };

  window.log = {
    init: init
  };

}).call(this);
