// Generated by CoffeeScript 1.8.0
(function() {
  var background, board, determine_shield_transparency, hp_indicator, mark_grid, piece_at, piece_drawing_types, shield_indicator;

  piece_drawing_types = {
    black: {
      pawn: '\u265F',
      super_pawn: '\u265F',
      knight: '\u265E',
      bishop: '\u265D',
      rook: '\u265C',
      queen: '\u265B',
      king: '\u265A'
    },
    white: {
      pawn: '\u2659',
      super_pawn: '\u2659',
      knight: '\u2658',
      bishop: '\u2657',
      rook: '\u2656',
      queen: '\u2655',
      king: '\u2654'
    }
  };

  hp_indicator = function(ctx, _arg, current, total) {
    var color_offset, green_offset, half, pos_x, pos_y, red_offset;
    pos_x = _arg[0], pos_y = _arg[1];
    half = settings.half_grid_size;
    total = 0.9 * total;
    current -= 0.1 * total;
    if (current < 0) {
      current = 0;
    }
    color_offset = Math.floor((total - current) / total * 255 * 2);
    red_offset = color_offset > 255 ? 255 : color_offset;
    green_offset = color_offset - red_offset;
    shape.set_style(ctx, "rgba(" + red_offset + ", " + (255 - green_offset) + ", 0, 0.9)");
    return shape.rectangle(ctx, pos_x + half - 7, pos_y - half, 7, 7, true);
  };

  determine_shield_transparency = function(total) {
    if (total <= 1) {
      return 0.4;
    } else if (total <= 3) {
      return 0.5;
    } else if (total <= 7) {
      return 0.6;
    } else if (total <= 13) {
      return 0.7;
    } else if (total <= 21) {
      return 0.8;
    } else {
      return 0.9;
    }
  };

  shield_indicator = function(ctx, _arg, current, total) {
    var cut_length, h, half, length, percentage, pos_x, pos_y, transparency, w, x, y;
    pos_x = _arg[0], pos_y = _arg[1];
    if (total === 0) {
      return;
    }
    half = settings.half_grid_size;
    length = settings.grid_size - 7;
    percentage = current / total;
    cut_length = (1 - percentage) * length;
    transparency = determine_shield_transparency(total);
    x = pos_x - half + cut_length;
    y = pos_y - half;
    w = length - cut_length;
    h = 7;
    shape.set_style(ctx, shape.style_white);
    shape.rectangle(ctx, x, y, w, h, true);
    shape.set_style(ctx, "rgba(0, 0, 255, " + transparency + ")");
    return shape.rectangle(ctx, x, y, w, h, true);
  };

  background = function(ctx, size) {
    var grid_size, x, y, _i, _j;
    ctx.save();
    grid_size = settings.grid_size;
    shape.set_style(ctx, shape.style_brown);
    for (x = _i = 0; grid_size > 0 ? _i < size : _i > size; x = _i += grid_size) {
      for (y = _j = 0; grid_size > 0 ? _j < size : _j > size; y = _j += grid_size) {
        if ((x + y) / grid_size % 2 !== 0) {
          shape.rectangle(ctx, x, y, grid_size, grid_size, true);
        }
      }
    }
    return ctx.restore();
  };

  piece_at = function(ctx, piece, _arg) {
    var color, half, pos_x, pos_y, type;
    pos_x = _arg[0], pos_y = _arg[1];
    color = piece.color;
    type = piece.type;
    half = settings.half_grid_size;
    shape.text(ctx, piece_drawing_types[color][type], pos_x - half + 5, pos_y - half + 40);
    shape.save_style(ctx);
    hp_indicator(ctx, [pos_x, pos_y], piece.hp, piece.hp_total);
    shield_indicator(ctx, [pos_x, pos_y], piece.shield, piece.shield_total);
    return shape.restore_style(ctx);
  };

  board = function(ctx) {
    var i, j, _i, _results;
    _results = [];
    for (i = _i = 1; _i <= 8; i = ++_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (j = _j = 1; _j <= 8; j = ++_j) {
          if (!window.board.instance.is_occupied([i, j])) {
            continue;
          }
          _results1.push(piece_at(ctx, window.board.instance.get_piece([i, j]), calc.coord_to_pos([i, j])));
        }
        return _results1;
      })());
    }
    return _results;
  };

  mark_grid = function(ctx, coord, style) {
    var grid_size, padding, x, y, _ref;
    padding = 2;
    grid_size = settings.grid_size;
    x = coord[0], y = coord[1];
    _ref = [(x - 1) * grid_size + padding, (y - 1) * grid_size + padding], x = _ref[0], y = _ref[1];
    ctx.save();
    ctx.lineWidth = 1 + (padding - 1) * 2;
    if (style != null) {
      shape.set_style(ctx, style);
    }
    shape.rectangle(ctx, x, y, grid_size - 2 * padding, grid_size - 2 * padding);
    return ctx.restore();
  };

  window.paint = {
    background: background,
    piece_at: piece_at,
    board: board,
    mark_grid: mark_grid
  };

}).call(this);
