// Generated by CoffeeScript 1.8.0
(function() {
  var background, mark_grid, piece, piece_at, piece_drawing_types;

  piece_drawing_types = {
    black: {
      pawn: '\u265F',
      knight: '\u265E',
      bishop: '\u265D',
      rook: '\u265C',
      queen: '\u265B',
      king: '\u265A'
    },
    white: {
      pawn: '\u2659',
      knight: '\u2658',
      bishop: '\u2657',
      rook: '\u2656',
      queen: '\u2655',
      king: '\u2654'
    }
  };

  background = function(ctx, size) {
    var grid_size, x, y, _i, _j;
    ctx.save();
    grid_size = settings.grid_size;
    shape.set_style(ctx, shape.style_brown);
    for (x = _i = 0; grid_size > 0 ? _i < size : _i > size; x = _i += grid_size) {
      for (y = _j = 0; grid_size > 0 ? _j < size : _j > size; y = _j += grid_size) {
        if ((x + y) / grid_size % 2 !== 0) {
          shape.rectangle(ctx, x, y, grid_size, grid_size, true);
        }
      }
    }
    return ctx.restore();
  };

  piece = function(ctx, piece) {
    return piece_at(ctx, piece, calc.coord_to_pos(piece.coordinate));
  };

  piece_at = function(ctx, piece, _arg) {
    var color, grid_size, pos_x, pos_y, type;
    pos_x = _arg[0], pos_y = _arg[1];
    color = piece.color;
    type = piece.type;
    grid_size = settings.grid_size;
    return shape.text(ctx, piece_drawing_types[color][type], pos_x - grid_size / 2 + 5, pos_y - grid_size / 2 + 40);
  };

  mark_grid = function(ctx, coord, style) {
    var grid_size, padding, x, y, _ref;
    padding = 2;
    grid_size = settings.grid_size;
    x = coord[0], y = coord[1];
    _ref = [(x - 1) * grid_size + padding, (y - 1) * grid_size + padding], x = _ref[0], y = _ref[1];
    ctx.save();
    ctx.lineWidth = 1 + (padding - 1) * 2;
    if (style != null) {
      shape.set_style(ctx, style);
    }
    shape.rectangle(ctx, x, y, grid_size - 2 * padding, grid_size - 2 * padding);
    return ctx.restore();
  };

  window.paint = {
    background: background,
    piece: piece,
    piece_at: piece_at,
    mark_grid: mark_grid
  };

}).call(this);
