// Generated by CoffeeScript 1.8.0
(function() {
  var Piece,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Piece = (function() {
    function Piece(color, type, coordinate, board) {
      var ability;
      this.color = color;
      this.type = type;
      this.coordinate = coordinate;
      this.board = board;
      this.on_recover_round = __bind(this.on_recover_round, this);
      this.on_attack_round_end = __bind(this.on_attack_round_end, this);
      this.on_attack_round_begin = __bind(this.on_attack_round_begin, this);
      this.on_assist_round_end = __bind(this.on_assist_round_end, this);
      this.on_assist_round_begin = __bind(this.on_assist_round_begin, this);
      ability = rule.ability[this.type];
      this.attack = ability['atk'];
      this.attack_cd = ability['atk_cd'];
      this.assistance = ability['ast'];
      this.hp_total = ability['hp'];
      this.shield_total_born = ability['shield'];
      this.shield_heal_born = ability['shield_heal'];
      this.move_cd = ability['move_cd'];
      this.hp = this.hp_total;
      this.shield = this.shield_total = this.shield_total_born;
      this.shield_heal = this.shield_heal_born;
      this.attack_cd_ticks = 0;
      this.move_cd_ticks = 0;
      ev.hook('assist_round_begin', this.on_assist_round_begin);
      ev.hook('assist_round_end', this.on_assist_round_end);
      ev.hook('attack_round_begin', this.on_attack_round_begin);
      ev.hook('attack_round_end', this.on_attack_round_end);
      ev.hook('recover_round', this.on_recover_round);
    }

    Piece.prototype.move_to = function(new_coord) {
      if (this.is_onboard()) {
        this.board.lift_piece(this.coordinate);
      }
      this.coordinate = new_coord;
      if (new_coord != null) {
        return this.board.place_piece(this);
      }
    };

    Piece.prototype.valid_moves = function() {
      return rule.move.strategies[this.type](this.color, this.coordinate, this.board);
    };

    Piece.prototype.is_onboard = function() {
      return this.coordinate != null;
    };

    Piece.prototype.on_assist_round_begin = function() {
      var astee, coord, _i, _len, _ref, _results;
      this.shield_total = this.shield_total_born;
      this.shield_heal = this.shield_heal_born;
      _ref = this.valid_moves().defensive;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        coord = _ref[_i];
        astee = this.board.get_piece(coord);
        _results.push(ev.trigger('battle_assist', {
          aster: this,
          astee: astee,
          coord_from: this.coordinate,
          coord_to: coord,
          enhancement: this.assistance
        }));
      }
      return _results;
    };

    Piece.prototype.on_assist_round_end = function() {
      if (this.shield > this.shield_total) {
        return this.shield = this.shield_total;
      }
    };

    Piece.prototype.on_attack_round_begin = function() {
      var coord, target, _i, _len, _ref;
      if (this.attack_cd_ticks > 0 || this.valid_moves().offensive.length === 0) {
        return;
      }
      _ref = this.valid_moves().offensive;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        coord = _ref[_i];
        target = this.board.get_piece(coord);
        ev.trigger('battle_attack', {
          atker: this,
          atkee: target,
          coord_from: this.coordinate,
          coord_to: coord,
          damage: calc.randint(this.attack)
        });
      }
      return this.attack_cd_ticks = this.attack_cd;
    };

    Piece.prototype.on_attack_round_end = function() {
      if (this.attack_cd_ticks > 0) {
        return this.attack_cd_ticks--;
      }
    };

    Piece.prototype.on_recover_round = function() {
      this.shield += this.shield_heal;
      if (this.shield > this.shield_total) {
        return this.shield = this.shield_total;
      }
    };

    Piece.prototype.inflict = function(damage) {
      if (this.shield >= damage) {
        this.shield -= damage;
      } else {
        damage -= this.shield;
        this.shield = 0;
        this.hp -= damage;
        ev.trigger('piece_hurt', {
          piece: this,
          coord: this.coordinate
        });
      }
      if (this.hp <= 0) {
        return this.die();
      }
    };

    Piece.prototype.enhance = function(assistance) {
      this.shield_total += assistance[0];
      return this.shield_heal += assistance[1];
    };

    Piece.prototype.recover = function(hp) {};

    Piece.prototype.die = function() {
      if (!this.is_onboard()) {
        return;
      }
      this.board.lift_piece(this.coordinate);
      this.coordinate = null;
      ev.unhook('assist_round_begin', this.on_assist_round_begin);
      ev.unhook('assist_round_end', this.on_assist_round_end);
      ev.unhook('attack_round_begin', this.on_attack_round_begin);
      ev.unhook('attack_round_end', this.on_attack_round_end);
      return ev.unhook('recover_round', this.on_recover_round);
    };

    Piece.prototype.info = function() {
      return "hp: " + (Math.floor(this.hp)) + "/" + this.hp_total + "\nshield: " + (Math.floor(this.shield)) + "/" + this.shield_total + " (" + this.shield_heal + ")";
    };

    return Piece;

  })();

  window.piece = {
    Piece: Piece
  };

}).call(this);
