// Generated by CoffeeScript 1.8.0
(function() {
  var Piece;

  Piece = (function() {
    function Piece(color, type, coordinate, board) {
      this.color = color;
      this.type = type;
      this.coordinate = coordinate;
      this.board = board;
    }

    Piece.prototype.move_to = function(new_coord) {
      if (this.is_onboard()) {
        this.board.lift_piece(this.coordinate);
      }
      this.coordinate = new_coord;
      if (new_coord != null) {
        return this.board.place_piece(this);
      }
    };

    Piece.prototype.is_onboard = function() {
      return this.coordinate != null;
    };

    return Piece;

  })();

  window.piece = {
    Piece: Piece
  };

}).call(this);
