// Generated by CoffeeScript 1.8.0
(function() {
  var Piece;

  Piece = (function() {
    function Piece(color, type, coordinate, board) {
      var ability;
      this.color = color;
      this.type = type;
      this.coordinate = coordinate;
      this.board = board;
      ability = rule.ability[this.type];
      this.attack = ability['atk'];
      this.attack_cd = ability['atk_cd'];
      this.assistance = ability['ast'];
      this.hp_total = ability['hp'];
      this.shield_total = ability['shield'];
      this.shield_heal = ability['shield_heal'];
      this.move_cd = ability['move_cd'];
      this.hp = 80;
      this.shield = 1;
      this.attack_cd_ticks = 0;
      this.move_cd_ticks = 0;
    }

    Piece.prototype.move_to = function(new_coord) {
      if (this.is_onboard()) {
        this.board.lift_piece(this.coordinate);
      }
      this.coordinate = new_coord;
      if (new_coord != null) {
        return this.board.place_piece(this);
      }
    };

    Piece.prototype.valid_moves = function() {
      return rule.move.strategies[this.type](this.color, this.coordinate, this.board);
    };

    Piece.prototype.is_onboard = function() {
      return this.coordinate != null;
    };

    return Piece;

  })();

  window.piece = {
    Piece: Piece
  };

}).call(this);
