// Generated by CoffeeScript 1.8.0
(function() {
  var cvs_border_width, cvs_size, grid_size, piece_font;

  cvs_border_width = 3;

  cvs_size = 400;

  grid_size = cvs_size / 8;

  piece_font = "40px Courier New";

  window.settings = {
    cvs_border_width: cvs_border_width,
    cvs_size: cvs_size,
    grid_size: grid_size,
    piece_font: piece_font
  };

}).call(this);
