// Generated by CoffeeScript 2.2.1
(function() {
  var ctx, cvs, disable_button, enable_button, init, init_cvs, message_timeout_obj, set_button_text, set_canvas_attr, show_message;

  ctx = {
    animate: null,
    static: null,
    background: null
  };

  cvs = {
    animate: null,
    static: null,
    background: null
  };

  init_cvs = function(name) {
    cvs[name] = document.getElementById(name);
    return ctx[name] = cvs[name].getContext('2d');
  };

  set_canvas_attr = function(cvs, z_index, size) {
    cvs.style.border = `solid #000 ${settings.cvs_border_width}px`;
    cvs.style.position = "absolute";
    cvs.style['z-index'] = `${z_index}`;
    return cvs.width = cvs.height = size;
  };

  set_button_text = function(button, text) {
    return button.innerHTML = text;
  };

  disable_button = function(button) {
    return button.disabled = 'disabled';
  };

  enable_button = function(button) {
    return button.disabled = void 0;
  };

  message_timeout_obj = null;

  show_message = function(message) {
    ui.message.innerHTML = message;
    clearTimeout(message_timeout_obj);
    return message_timeout_obj = setTimeout((function() {
      return ui.message.innerHTML = '';
    }), 5000);
  };

  init = function() {
    init_cvs('background');
    init_cvs('static');
    init_cvs('animate');
    ui.cvs_bounding_rect = cvs.animate.getBoundingClientRect();
    set_canvas_attr(cvs.background, 1, settings.cvs_size);
    set_canvas_attr(cvs.static, 2, settings.cvs_size);
    set_canvas_attr(cvs.animate, 3, settings.cvs_size);
    ctx.static.font = settings.piece_font;
    ctx.animate.font = settings.piece_font;
    paint.background(ctx.background, settings.cvs_size);
    ui.info = document.getElementById('info');
    ui.message = document.getElementById('message');
    ui.player_id = document.getElementById('player_id');
    ui.opponent_id = document.getElementById('opponent_id');
    ui.login_button = document.getElementById('login');
    ui.challenge_button = document.getElementById('challenge');
    ui.spawntime = document.getElementById('spawntime');
    return ui.gamestat = document.getElementById('gamestat');
  };

  window.ui = {
    init,
    set_button_text,
    disable_button,
    enable_button,
    show_message,
    cvs,
    ctx,
    cvs_bounding_rect: null,
    info: null,
    message: null,
    player_id: null,
    opponent_id: null,
    login_button: null,
    challenge_button: null,
    spawntime: null,
    gamestat: null
  };

}).call(this);

//# sourceMappingURL=ui.js.map
