// Generated by CoffeeScript 1.8.0
(function() {
  var arrow, line, set_style, triangle;

  arrow = function(ctx, x, y, to_x, to_y, size) {
    var angle, delta_x, delta_y;
    if (size == null) {
      size = 10;
    }
    line(ctx, x, y, to_x, to_y);
    delta_x = to_x - x;
    delta_y = to_y - y;
    if (delta_y === 0) {
      angle = delta_x < 0 ? Math.PI : 0;
    } else {
      angle = Math.atan(delta_x / delta_y);
    }
    ctx.save();
    ctx.translate(to_x, to_y);
    ctx.rotate(angle + Math.PI / 2);
    triangle(ctx, 0, -size, -size / 2, 0, size / 2, 0);
    return ctx.restore();
  };

  line = function(ctx, x, y, to_x, to_y) {
    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(to_x, to_y);
    ctx.stroke();
    return ctx.closePath();
  };

  triangle = function(ctx, x1, y1, x2, y2, x3, y3) {
    ctx.beginPath();
    ctx.moveTo(x1, y1);
    ctx.lineTo(x2, y2);
    ctx.lineTo(x3, y3);
    return ctx.fill();
  };

  set_style = function(ctx, style) {
    return ctx.strokeStyle = ctx.fillStyle = style;
  };

  window.util = {
    arrow: arrow,
    line: line,
    triangle: triangle,
    set_style: set_style
  };

}).call(this);
