// Generated by CoffeeScript 1.8.0
(function() {
  var get_state, set_state;

  get_state = function() {
    return calc.to_string({
      board_state: board.get_state(),
      effect_state: effect.get_state()
    });
  };

  set_state = function(str) {
    var state;
    state = calc.from_string(str);
    board.set_state(state.board_state);
    return effect.set_state(state.effect_state);
  };

  window.gamestate = {
    get_state: get_state,
    set_state: set_state
  };

}).call(this);
