// Generated by CoffeeScript 1.8.0
(function() {
  var assist_round, attack_round, game_loop_obj, move_round, next_gametick, recover_round, render_gametick, start, stop;

  move_round = function() {
    ev.trigger_now('move_round_begin', {});
    ev.trigger_now('move_round', {});
    return ev.trigger_now('move_round_end', {});
  };

  assist_round = function() {
    ev.trigger_now('assist_round_begin', {});
    ev.trigger_now('assist_round', {});
    return ev.trigger_now('assist_round_end', {});
  };

  recover_round = function() {
    ev.trigger_now('recover_round_begin', {});
    ev.trigger_now('recover_round', {});
    return ev.trigger_now('recover_round_end', {});
  };

  attack_round = function() {
    ev.trigger_now('attack_round_begin', {});
    ev.trigger_now('attack_round', {});
    return ev.trigger_now('attack_round_end', {});
  };

  render_gametick = function() {
    shape.clear_canvas(ui.ctx["static"]);
    return ev.trigger_now('render', {});
  };

  next_gametick = function() {
    return ev.trigger('gametick', {});
  };

  game_loop_obj = null;

  start = function() {
    return game_loop_obj = setInterval(next_gametick, 100);
  };

  stop = function() {
    return clearInterval(game_loop_obj);
  };

  window.game = {
    start: start,
    stop: stop,
    init_demo: null,
    init_host: null,
    init_guest: null,
    init_observer: null,
    move_round: move_round,
    assist_round: assist_round,
    recover_round: recover_round,
    attack_round: attack_round,
    render_gametick: render_gametick
  };

}).call(this);
