// Generated by CoffeeScript 2.2.1
(function() {
  var ai_think_round, assist_round, attack_round, game_loop_obj, move_round, next_gametick, recover_round, render_gametick, start, stop;

  move_round = function(board) {
    ev.trigger_now('move_round_begin', {board});
    ev.trigger_now('move_round', {board});
    return ev.trigger_now('move_round_end', {board});
  };

  assist_round = function(board) {
    ev.trigger_now('assist_round_begin', {board});
    ev.trigger_now('assist_round', {board});
    return ev.trigger_now('assist_round_end', {board});
  };

  recover_round = function(board) {
    ev.trigger_now('recover_round_begin', {board});
    ev.trigger_now('recover_round', {board});
    return ev.trigger_now('recover_round_end', {board});
  };

  attack_round = function(board) {
    ev.trigger_now('attack_round_begin', {board});
    ev.trigger_now('attack_round', {board});
    return ev.trigger_now('attack_round_end', {board});
  };

  ai_think_round = function(board) {
    return ev.trigger_now('ai_think_round', {board});
  };

  render_gametick = function() {
    shape.clear_canvas(ui.ctx.static);
    return ev.trigger_now('render', {});
  };

  next_gametick = function() {
    return ev.trigger('gametick', {});
  };

  game_loop_obj = null;

  start = function() {
    return game_loop_obj = setInterval(next_gametick, 100);
  };

  stop = function() {
    return clearInterval(game_loop_obj);
  };

  window.game = {
    start,
    stop,
    init_demo: null,
    init_host: null,
    init_guest: null,
    init_observer: null,
    move_round,
    assist_round,
    recover_round,
    attack_round,
    ai_think_round,
    render_gametick
  };

}).call(this);

//# sourceMappingURL=game.js.map
