// Generated by CoffeeScript 2.2.1
(function() {
  var get_mouse_pos, init, on_user_mousedown, on_user_mousemove, on_user_mouseup;

  get_mouse_pos = function(evt) {
    var mouse_x, mouse_y;
    mouse_x = evt.clientX - ui.cvs_bounding_rect.left - settings.cvs_border_width;
    mouse_y = evt.clientY - ui.cvs_bounding_rect.top - settings.cvs_border_width;
    return [mouse_x, mouse_y];
  };

  on_user_mousedown = function(evt) {
    var pos;
    pos = get_mouse_pos(evt);
    return ev.trigger('mousedown', {pos});
  };

  on_user_mouseup = function(evt) {
    var pos;
    pos = get_mouse_pos(evt);
    return ev.trigger('mouseup', {pos});
  };

  on_user_mousemove = function(evt) {
    var pos;
    pos = get_mouse_pos(evt);
    return ev.trigger('mousemove', {pos});
  };

  init = function() {
    ui.cvs.animate.addEventListener("mousedown", on_user_mousedown, false);
    ui.cvs.animate.addEventListener("mouseup", on_user_mouseup, false);
    return ui.cvs.animate.addEventListener("mousemove", on_user_mousemove, false);
  };

  window.input = {init};

}).call(this);
