// Generated by CoffeeScript 2.2.1
(function() {
  var init, logging_evts, on_gametick, tick_count;

  tick_count = 0;

  on_gametick = function() {
    tick_count++;
    if (tick_count % 100 === 0) {
      return console.log('tick', tick_count);
    }
  };

  logging_evts = ['pick', 'drop', 'battle_assist'];

  init = function() {
    var evt_name, i, len, results;
    ev.hook('gametick', on_gametick);
    results = [];
    for (i = 0, len = logging_evts.length; i < len; i++) {
      evt_name = logging_evts[i];
      results.push(ev.hook(evt_name, (function(evt_name) {
        return function(evt) {
          return console.log(evt_name);
        };
      })(evt_name)));
    }
    return results;
  };

  window.log = {init};

}).call(this);
