// Generated by CoffeeScript 2.2.1
(function() {
  var handle_cached_operations, handle_operation, init, is_valid_operation, on_game_operation, on_network_operation_in, operation_queue, send_cached_operations;

  operation_queue = []; // queue of user operation

  handle_cached_operations = function() {
    var results;
    results = [];
    while (operation_queue.length > 0) {
      results.push(handle_operation(operation_queue.shift()));
    }
    return results;
  };

  send_cached_operations = function() {
    var i, len, op;
    for (i = 0, len = operation_queue.length; i < len; i++) {
      op = operation_queue[i];
      ev.trigger_now('network_out_operation', {
        operation: calc.to_string(op)
      });
    }
    return operation_queue = [];
  };

  is_valid_operation = function(op_evt) {
    var authentic_piece, moves;
    if (!board.instance.is_occupied(op_evt.piece.coordinate)) {
      return false;
    }
    authentic_piece = board.instance.get_piece(op_evt.piece.coordinate);
    if (!piece.equal(authentic_piece, op_evt.piece)) { // replace this with unique piece identity
      return false;
    }
    if (!authentic_piece.can_move()) {
      return false;
    }
    moves = authentic_piece.valid_moves();
    if (calc.coord_one_of(op_evt.coord_to, moves.regular)) {
      return true;
    } else {
      return false;
    }
  };

  handle_operation = function(op_evt) {
    var authentic_piece;
    if (is_valid_operation(op_evt)) {
      authentic_piece = board.instance.get_piece(op_evt.piece.coordinate);
      return ev.trigger('battle_move', {
        piece: authentic_piece,
        coord_to: op_evt.coord_to
      });
    }
  };

  on_network_operation_in = function(evt) {
    var op;
    op = calc.from_string(evt.operation);
    calc.set_type(op.piece, piece.Piece);
    return operation_queue.push(op);
  };

  on_game_operation = function(evt) {
    return operation_queue.push(evt);
  };

  init = function() {
    ev.hook('op_movepiece', on_game_operation);
    return ev.hook('network_in_operation', on_network_operation_in);
  };

  window.operation = {init, handle_cached_operations, send_cached_operations};

}).call(this);
