// Generated by CoffeeScript 2.2.1
(function() {
  var cvs_border_width, cvs_size, grid_size, half_grid_size, piece_font;

  cvs_border_width = 3;

  cvs_size = 400;

  grid_size = cvs_size / 8;

  piece_font = "40px Courier New";

  half_grid_size = grid_size / 2;

  window.settings = {cvs_border_width, cvs_size, grid_size, half_grid_size, piece_font};

}).call(this);
