// Generated by CoffeeScript 2.2.1
(function() {
  var arrow, clear_canvas, line, rectangle, restore_style, save_style, saved_fillstyle, saved_linewidth, saved_strokestyle, set_linewidth, set_style, style_blue, style_blue_tp, style_brown, style_green_tp, style_grey, style_light, style_red_tp, style_tp, style_white, text, triangle;

  arrow = function(ctx, x, y, to_x, to_y, size = 5) {
    var angle;
    line(ctx, x, y, to_x, to_y);
    angle = calc.get_segment_angle(x, y, to_x, to_y);
    ctx.save();
    ctx.translate(to_x, to_y);
    ctx.rotate(angle);
    triangle(ctx, 0, 0, -size / 2, size, size / 2, size);
    return ctx.restore();
  };

  line = function(ctx, x, y, to_x, to_y) {
    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(to_x, to_y);
    ctx.stroke();
    return ctx.closePath();
  };

  triangle = function(ctx, x1, y1, x2, y2, x3, y3) {
    ctx.beginPath();
    ctx.moveTo(x1, y1);
    ctx.lineTo(x2, y2);
    ctx.lineTo(x3, y3);
    return ctx.fill();
  };

  rectangle = function(ctx, x, y, width, height, fill = false) {
    if (fill) {
      return ctx.fillRect(x, y, width, height);
    } else {
      return ctx.strokeRect(x, y, width, height);
    }
  };

  text = function(ctx, text, x, y, style, font) {
    if (style != null) {
      save_style(ctx);
      set_style(ctx, style);
    }
    if (font != null) {
      ctx.font = font;
    }
    ctx.fillText(text, x, y);
    if (font != null) {
      ctx.font = settings.piece_font;
    }
    if (style != null) {
      return restore_style(ctx);
    }
  };

  clear_canvas = function(ctx) {
    ctx.save();
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
    return ctx.restore();
  };

  set_style = function(ctx, style) {
    return ctx.strokeStyle = ctx.fillStyle = style;
  };

  set_linewidth = function(ctx, width) {
    return ctx.lineWidth = width;
  };

  // state
  saved_strokestyle = [];

  saved_fillstyle = [];

  saved_linewidth = [];

  save_style = function(ctx) {
    saved_strokestyle.push(ctx.strokeStyle);
    saved_fillstyle.push(ctx.fillStyle);
    return saved_linewidth.push(ctx.lineWidth);
  };

  restore_style = function(ctx) {
    ctx.strokeStyle = saved_strokestyle.pop();
    ctx.fillStyle = saved_fillstyle.pop();
    return ctx.lineWidth = saved_linewidth.pop();
  };

  // constant
  style_red_tp = "rgba(255, 0, 0, 0.7)";

  style_green_tp = "rgba(0, 255, 0, 0.7)";

  style_blue_tp = "rgba(0, 0, 255, 0.7)";

  style_tp = "rgba(0, 0, 0, 0.5)";

  style_white = "#FFF";

  style_blue = "#BBF";

  style_brown = "#BB9";

  style_grey = "#DDD";

  style_light = "#888";

  window.shape = {arrow, line, triangle, rectangle, text, clear_canvas, set_style, save_style, restore_style, style_red_tp, style_green_tp, style_blue_tp, style_white, style_brown, style_blue, style_grey, style_light, style_tp};

}).call(this);

//# sourceMappingURL=shape.js.map
