// Generated by CoffeeScript 1.8.0
(function() {
  var activate, ai_color, deactivate, init, on_think, set_interval, think_interval, thinking_cooldown;

  think_interval = 10;

  thinking_cooldown = think_interval;

  ai_color = null;

  init = function() {};

  activate = function(color) {
    ev.hook('ai_think_round', on_think);
    return ai_color = color;
  };

  deactivate = function() {
    return ev.unhook('ai_think_round', on_think);
  };

  on_think = function() {
    var op;
    if (thinking_cooldown === 0) {
      op = ai.monkey.think_of_one_operation(board.instance, ai_color);
      if (op !== 'abort') {
        ev.trigger('op_movepiece', op);
      }
      return thinking_cooldown = think_interval;
    } else {
      return thinking_cooldown--;
    }
  };

  set_interval = function(interval) {
    return think_interval = Math.floor(interval * 10);
  };

  window.ai = {
    init: init,
    activate: activate,
    deactivate: deactivate,
    set_interval: set_interval,
    monkey: null
  };

}).call(this);
