// Generated by CoffeeScript 2.2.1
(function() {
  var activate, ai_color, ai_current, deactivate, init, on_think, set_ai, set_interval, think_interval, thinking_cooldown;

  think_interval = 10;

  thinking_cooldown = think_interval;

  ai_color = null;

  ai_current = null;

  init = function() {};

  activate = function(color) {
    ev.hook('ai_think_round', on_think);
    return ai_color = color;
  };

  deactivate = function() {
    return ev.unhook('ai_think_round', on_think);
  };

  on_think = function() {
    var op;
    if (ai_current == null) {
      return;
    }
    if (thinking_cooldown === 0) {
      op = ai_current.think_of_one_operation(calc.clone(board.instance), ai_color);
      if (op !== 'abort') {
        ev.trigger('op_movepiece', op);
      }
      return thinking_cooldown = think_interval;
    } else {
      return thinking_cooldown--;
    }
  };

  set_interval = function(interval) {
    return think_interval = Math.floor(interval * 10);
  };

  set_ai = function(ai_number) {
    var all_ai;
    all_ai = [null, ai.monkey, ai.dolphin];
    return ai_current = all_ai[ai_number];
  };

  window.ai = {
    init,
    activate,
    deactivate,
    set_interval,
    set_ai,
    monkey: null,
    dolphin: null
  };

}).call(this);
