// Generated by CoffeeScript 2.2.1
(function() {
  var think_of_one_operation, try_moving_piece;

  try_moving_piece = function(board, piece, coord) {
    var moves;
    if (!piece.can_move()) {
      return 'no moves';
    }
    moves = board.get_valid_regular_moves(coord);
    if (moves.length > 0) {
      return calc.pick_one(moves);
    } else {
      return 'no moves';
    }
  };

  think_of_one_operation = function(board, color) {
    var all_moves, coord, current_piece, p, ref, result_coord, x;
    all_moves = [];
    ref = board.all_pieces();
    for (x of ref) {
      [coord, p] = x;
      current_piece = board.get_piece(coord);
      if (current_piece.color !== color) {
        continue;
      }
      result_coord = try_moving_piece(board, current_piece, coord);
      if (result_coord !== 'no moves') {
        all_moves.push({
          piece: current_piece,
          coord_to: result_coord,
          coord_from: coord
        });
      }
    }
    if (all_moves.length > 0) {
      return calc.pick_one(all_moves);
    } else {
      return 'abort';
    }
  };

  window.ai.monkey = {think_of_one_operation};

}).call(this);

//# sourceMappingURL=monkey.js.map
