// Generated by CoffeeScript 1.8.0
(function() {
  var think_of_one_operation, try_moving_piece;

  try_moving_piece = function(piece) {
    var moves;
    if (!piece.can_move()) {
      return 'no moves';
    }
    moves = piece.valid_moves();
    if (moves.regular.length > 0) {
      return calc.pick_one(moves.regular);
    } else {
      return 'no moves';
    }
  };

  think_of_one_operation = function(board, color) {
    var all_moves, current_piece, i, j, result_coord, _i, _j;
    all_moves = [];
    for (i = _i = 1; _i <= 8; i = ++_i) {
      for (j = _j = 1; _j <= 8; j = ++_j) {
        if (!board.is_occupied([j, i])) {
          continue;
        }
        current_piece = board.get_piece([j, i]);
        if (current_piece.color !== color) {
          continue;
        }
        result_coord = try_moving_piece(current_piece);
        if (result_coord !== 'no moves') {
          all_moves.push({
            piece: current_piece,
            coord_to: result_coord
          });
        }
      }
    }
    if (all_moves.length > 0) {
      return calc.pick_one(all_moves);
    } else {
      return 'abort';
    }
  };

  window.ai.monkey = {
    think_of_one_operation: think_of_one_operation
  };

}).call(this);
